version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    depends_on: 
      - db
