CREATE SCHEMA IF NOT EXISTS statcast;

CREATE TABLE IF NOT EXISTS statcast.pitches (
    game_pk INTEGER NOT NULL,
    game_type VARCHAR NOT NULL,
    game_date DATE NOT NULL,
    home_team VARCHAR NOT NULL,
    away_team VARCHAR NOT NULL,
    pitch_type VARCHAR,    
    pitch_name VARCHAR,
    pitcher_id VARCHAR NOT NULL,
    pitcher_name VARCHAR NOT NULL,
    pitcher_handedness VARCHAR NOT NULL,
    batter_id INTEGER NOT NULL,
    batter_name VARCHAR NOT NULL,
    batter_handedness VARCHAR NOT NULL,
    inning INTEGER NOT NULL,
    inning_topbot VARCHAR NOT NULL,
    outs_when_up INTEGER NOT NULL,
    at_bat_number INTEGER NOT NULL,
    pitch_number INTEGER NOT NULL,
    release_speed FLOAT,
    release_pos_x FLOAT,
    release_pos_z FLOAT,
    spin_axis FLOAT,
    events VARCHAR,
    description VARCHAR NOT NULL,
    zone FLOAT,
    des VARCHAR,
    type VARCHAR NOT NULL,
    hit_location FLOAT,
    bb_type VARCHAR,
    balls INTEGER NOT NULL,
    strikes INTEGER NOT NULL,
    pfx_x FLOAT,
    pfx_z FLOAT,
    plate_x FLOAT,
    plate_z FLOAT,
    hc_x FLOAT,
    hc_y VARCHAR,
    vx0 FLOAT,
    vy0 FLOAT,
    vz0 FLOAT,
    ax FLOAT,
    ay FLOAT,
    az FLOAT,
    sz_top FLOAT,
    sz_bot FLOAT,
    hit_distance_sc FLOAT,
    launch_speed FLOAT,
    launch_angle FLOAT,
    effective_speed FLOAT,
    release_spin_rate FLOAT,
    release_extension FLOAT,
    release_pos_y FLOAT,
    estimated_ba_using_speedangle FLOAT,
    estimated_woba_using_speedangle FLOAT,
    launch_speed_angle FLOAT,
    home_score INTEGER NOT NULL,
    post_home_score INTEGER NOT NULL,
    away_score INTEGER NOT NULL,
    post_away_score INTEGER NOT NULL
);

COPY statcast.pitches
FROM '/docker-entrypoint-initdb.d/statcast-all-time.csv'
DELIMITER ','
CSV HEADER;